### ISSUE TITLE
it is possible for wargs to keep original quotes?

### ISSUE THREAD

**Issue by iamqiz** [idigdoug/TextTools#3]
wargs will remove quotes, see below 
```
>echo a "y t" b
a "y t" b

>echo a "y t" b| wargs -I {} echo 123 {} 789
123 a y t b 789

>echo a "y t" b| wargs -I {} cmd /c echo 123 {} 789
123 "a y t b" 789
```
I expect it to output `123 a "y t" b 789`
it is possible?
thanks

**Comment by idigdoug** [comment]
Good question. I'll have to think about possible options.

**Comment by idigdoug** [comment]
I've reviewed this and it's confusing.

Part of what you are seeing is the behavior specified by Posix. By default, the input to xargs goes through a tokenizer, and the tokenizer removes the quotes. Without `-I`, we stop reading at the end of word. With `-I`, we stop reading at the end of line. In both cases, the quotes are removed. In your case, you end up with one token, `a y t b`.

I also see that you have an `echo.exe` program on your path, and that program appears to be removing quotes. The `cmd /c echo` is accurately showing what `wargs` is doing.

This is required behavior of xargs. You can change this by using the `-d` parameter. For example, if I use `-d\n`, I get a single `a "y t" b` token.

If I do that, I do get some behavior that is a bit different from xargs on Linux. I end up with output `123 "a \"y t\" b" 789`. This is by design, and the right thing to do most of the time, but it can be confusing. It is due to the way Windows handles command-line parameter tokens.

On Linux, xargs can directly pass each token to the command as a single argument in the argument list. On Windows, there is no argument list -- there is only a single command-line string (the C runtime turns the command-line string into an argument list, but not every program uses the C runtime's argument list, and `cmd /c echo` does not).

The current behavior of wargs is designed for programs that use the C runtime's argument list. It escapes the command-line string so that the C runtime argument list will be what you asked for. Since `cmd /c echo` does not use the C runtime argument list, it doesn't work perfectly with wargs. On the other hand, I suspect that this will actually work pretty well for your `echo.exe` program.

I might add a command-line switch to change the behavior to adjust for that case.
