### ISSUE TITLE
wargs not able to launch scripts with PATHEXT

### ISSUE THREAD

**Issue by WyntrHeart** [idigdoug/TextTools#4]
If I give wargs a binary executable command like `explorer` without the extension it works fine, but if I try to use one of my .cmd files by just typing the name without specifying the extension I get an error message that says `wargs: error : CreateProcessW error 2 starting name-of-script-here`. `.CMD` is in my PATHEXT variable, and works as expected outside of wargs

**Comment by idigdoug** [comment]
At present, this is by-design due to the behavior of CreateProcessW on Windows. You need to directly specify the name of the script processor. You'll usually do this by using something like `cmd /c name-of-script.cmd`. Other tools might use something like ShellExecute instead of CreateProcess, but that has other trade-offs that I don't like.

**Comment by WyntrHeart** [comment]
I haven't had to specify the processor to workaround this actually, simply typing the command name with the file extension is sufficient

**Comment by sergeevabc** [comment]
Dear @idigdoug, consider adding examples of how to use `wargs`, because no matter how hard I try, nothing works. In the end I moved to [xargswin](https://github.com/manasmbellani/xargswin) by @manasmbellani, then to [rush](https://github.com/shenwei356/rush) by @shenwei356.

**Comment by idigdoug** [comment]
> Dear [@idigdoug](https://github.com/idigdoug), consider adding examples of how to use `wargs`, because no matter how hard I try, nothing works. In the end I moved to [xargswin](https://github.com/manasmbellani/xargswin) by [@manasmbellani](https://github.com/manasmbellani), then to [rush](https://github.com/shenwei356/rush) by [@shenwei356](https://github.com/shenwei356).

Please clarify what doesn't work. What are you trying to do? What did you try? What happened when you tried it?

**Comment by sergeevabc** [comment]
# Mission

Find Bible translations that do not mention Satan and delete them.

# Win (that brings bliss and joy)

``` console
$ wget -A *.txt -nd -np -r https://openbible.com/textfiles/
$ grep -iL satan *.txt | xargswin -I {} del {}
$ grep -iL satan *.txt | rush del {}
```

# Fail (that brings confusion and frustration)

``` console
$ grep -iL satan *.txt | wargs -I {} del {}
wargs: error : CreateProcessW error 2 starting del
```

# Exodus

Now, you would say `wargs -I {} cmd /c del {}` is the way to go. However, it increases the level of complexity that should have been prevented during the development, as the two apps mentioned above did. Why? Because not a user for a computer, but a computer for a user. [KISS](https://en.wikipedia.org/wiki/KISS_principle). But since you have decided that this is the way to go, I suggest adding a couple of how-to examples to the main page so that people don't suffer in vain and can get from afar what awaits them.
